services:
  mysql:
    image: mysql
    container_name: mysql-gamearena
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gamearena-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-gamearena
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: main
      DB_URL: ${URL}
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "${APPLICATION_PORT}:8080"
    depends_on:
      - mysql
    networks:
      - gamearena-network
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
    driver: local

networks:
  gamearena-network:
    driver: bridge