### Fazer Login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Criar um novo usuario
# Precisa de autenticação como admin
POST http://localhost:8080/users/register
Content-Type: application/json
Authorization: Bearer SEU_TOKEN_AQUI

{
  "email": "test@gmail.com",
  "password": "1234",
  "role": "ROLE_USER"
}

### Listar inscrições
# Precisa de autenticação
GET http://localhost:8080/inscricoes?
    page={{$random.integer(100)}}&
    size={{$random.integer(100)}}
Authorization: Bearer SEU_TOKEN_AQUI

### Nova inscrição
POST http://localhost:8080/inscricoes/registrar
Content-Type: application/json

{
  "nomeCompleto": "",
  "nickname": "",
  "email": "",
  "dataNascimento": "",
  "comprovantePagamento": "",
  "aceitouTermos": false,
  "pagamento": false,
  "ativo": true
}

### Buscar um incrição por ID
# Precisa estar autenticação
GET http://localhost:8080/inscricoes/1
Authorization: Bearer SEU_TOKEN_AQUI

### Atualizar uma inscrição
# Precisa estar autenticação
PUT http://localhost:8080/inscricoes/1
Content-Type: application/json
Authorization: Bearer SEU_TOKEN_AQUI

{
  "nomeCompleto": "",
  "nickname": "",
  "email": "",
  "dataNascimento": "",
  "comprovantePagamento": "",
  "aceitouTermos": false,
  "dataInscricao": "",
  "pagamento": true
}

### Deletar uma inscrção
# Precisa de autenticação
DELETE http://localhost:8080/inscricoes/
Authorization: Bearer SEU_TOKEN_AQUI
